language: python

env:
  global:
    - DB_USERNAME=$RDSNAME
    - DB_PASSWORD=$RDSPW
    - DB_HOST=$RDSHOST
    - AWS_ACCESS_KEY_ID=$S3_ACCESSKEYID
    - AWS_SECRET_ACCESS_KEY=$S3_SECRETACCESSKEY

python:
  - "3.7"

install:
  - pip install -r backend/requirements.txt
  # - cd frontend && npm install && yarn build && cd ..
  - if [ "$TRAVIS_BRANCH" = "main" ]; then echo 'export const API_ENDPOINT = "https://nyuinterviewapp.com";' > frontend/src/Components/api.js; else echo 'export const API_ENDPOINT = "https://nyuinterviewappdevelop.com";' > frontend/src/Components/api.js; fi

script:
  - coverage run backend/manage.py test backend
  - black --check backend
  - flake8 backend

after_script:
  - cd $TRAVIS_BUILD_DIR
  - coveralls

before_deploy:
  - cd backend

deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: "us-east-1"
    app: $EBAPPNAME
    env: $EBENVNAME
    bucket_name: "elasticbeanstalk-us-east-1-076563148632"
    on:
      repo: gcivil-nyu-org/INET-Wednesday-Spring2023-Team-3
      branch:
        - $BRANCHNAME
  - provider: s3
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    bucket: $BUCKETNAME
    local_dir: $TRAVIS_BUILD_DIR/frontend/build
    skip_cleanup: true
    on:
      branch: $BRANCHNAME
