# Generated by Django 3.2 on 2023-04-09 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0002_alter_question_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionSubmissionCode",
            fields=[
                ("sub_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sub_text",
                    models.TextField(
                        max_length=10000, verbose_name="Submitted Code for the Question"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionStarterCode",
            fields=[
                ("sc_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sc_text",
                    models.TextField(
                        max_length=10000, verbose_name="Starter Code for the Question"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
