# Generated by Django 3.2 on 2023-04-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codinganswers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionstartercode",
            name="language",
            field=models.TextField(
                default="", max_length=30, verbose_name="Programming language"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionsubmissioncode",
            name="language",
            field=models.TextField(
                default="", max_length=30, verbose_name="Programming language"
            ),
            preserve_default=False,
        ),
    ]
