# Generated by Django 3.2 on 2023-04-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_companyprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="img_file",
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="studentalumniprofile",
            name="img_file",
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=""),
        ),
    ]
