# Generated by Django 3.2 on 2023-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_auto_20230506_0154"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentalumniprofile",
            name="degree_subject",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
