# Generated by Django 3.2 on 2023-05-08 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_studentalumniprofile_degree_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentalumniprofile",
            name="github_link",
            field=models.URLField(
                validators=[
                    django.core.validators.RegexValidator("^https://github.com/*")
                ]
            ),
        ),
        migrations.AlterField(
            model_name="studentalumniprofile",
            name="linkedin_link",
            field=models.URLField(
                validators=[
                    django.core.validators.RegexValidator(
                        "^https://www.linkedin.com/in/*"
                    )
                ]
            ),
        ),
    ]
