# Generated by Django 3.2 on 2023-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='userType',
            field=models.CharField(choices=[('Student/Alumni', 'Student/Alumni'), ('Recruiter', 'Recruiter')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
