# Generated by Django 4.1.5 on 2023-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nyuapp", "0002_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "text",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
