# Generated by Django 3.2 on 2023-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="img_file",
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=""),
        ),
    ]
