# Generated by Django 3.2 on 2023-04-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answerrecordings", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="ans_id",
            new_name="answer",
        ),
    ]
