# Generated by Django 3.2 on 2023-04-03 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answerrecordings", "0003_rename_ans_id_comment_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
