# Generated by Django 3.2 on 2023-04-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answerrecordings", "0005_auto_20230403_2009"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="A rating value is valid between 1 and 10",
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 10)),
                name="A rating value is valid between 1 and 10",
            ),
        ),
    ]
