# Generated by Django 3.2 on 2023-04-09 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("answerrecordings", "0006_auto_20230403_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=16,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.myuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dropbox",
            name="user",
            field=models.ForeignKey(
                default=16,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.myuser",
            ),
            preserve_default=False,
        ),
    ]
